version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go

  - package-ecosystem: gomod
    directory: "/fixtures/scan-targets/go-bad"
    schedule:
      interval: monthly
    labels:
      - dependencies
      - fixtures

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
