package html

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html/template"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/Smponi/sarifToHtml/internal/report"
)

// TemplateDataVersion identifies the renderer-facing data contract available to
// custom templates. Increment it only for intentional breaking changes.
const TemplateDataVersion = "sarif-html.template.v1"

// Options controls report metadata and source link generation.
type Options struct {
	// Title overrides reportData.Title when non-empty.
	Title string
	// TemplatePath points at a custom Go html/template file or directory. When
	// empty, the embedded default template is used.
	TemplatePath string
	// RepoURL and Revision build provider-specific source links when no custom
	// SourceURLTemplate is provided.
	RepoURL  string
	Revision string
	// SourceURLTemplate is the most flexible linking mode and supports
	// placeholders such as {path}, {revision}, and {lineFragment}.
	SourceURLTemplate string
}

// Render turns reportData into an HTML document. With the default template, the
// generated bytes contain all CSS and JavaScript needed to inspect the report
// offline.
func Render(reportData report.Report, options Options) ([]byte, error) {
	if options.Title == "" {
		options.Title = reportData.Title
	}
	if options.Title == "" {
		options.Title = "SARIF HTML Report"
	}

	data := NewTemplateData(reportData, options)
	return RenderTemplateData(data, options)
}

// RenderTemplateData renders a prebuilt TemplateData value with the embedded or
// custom template. It is useful for dry-run validation and tests that need the
// exact same versioned data contract used by Render.
func RenderTemplateData(data TemplateData, options Options) ([]byte, error) {
	tmpl, err := loadTemplate(options.TemplatePath, options)
	if err != nil {
		return nil, err
	}

	var output bytes.Buffer
	if err := tmpl.ExecuteTemplate(&output, "report", data); err != nil {
		return nil, fmt.Errorf("render HTML report: %w", err)
	}
	return output.Bytes(), nil
}

// MarshalTemplateData returns the versioned template data as stable,
// human-readable JSON for template authors and CI validation workflows.
func MarshalTemplateData(data TemplateData) ([]byte, error) {
	output, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal template data: %w", err)
	}
	return append(output, '\n'), nil
}

// TemplateData is the stable, versioned data contract exposed to custom report
// templates. It intentionally mirrors the useful renderer data without making
// the private renderer implementation part of the public template API.
type TemplateData struct {
	SchemaVersion string           `json:"schemaVersion"`
	Report        TemplateReport   `json:"report"`
	Title         string           `json:"title"`
	GeneratedAt   string           `json:"generatedAt"`
	Severities    []Count          `json:"severities"`
	Sources       []Count          `json:"sources"`
	ToolGroups    []ToolGroup      `json:"toolGroups"`
	Rules         []Count          `json:"rules"`
	Files         []Count          `json:"files"`
	Baseline      TemplateBaseline `json:"baseline"`
}

// TemplateReport is the report shape exposed to TemplateData v1.
type TemplateReport struct {
	Title    string            `json:"title"`
	Sources  []string          `json:"sources"`
	Findings []TemplateFinding `json:"findings"`
	Summary  TemplateSummary   `json:"summary"`
}

// TemplateSummary stores aggregate counts exposed to TemplateData v1.
type TemplateSummary struct {
	Total           int            `json:"total"`
	BySeverity      map[string]int `json:"bySeverity"`
	ByTool          map[string]int `json:"byTool"`
	ByRule          map[string]int `json:"byRule"`
	ByFile          map[string]int `json:"byFile"`
	ByBaselineState map[string]int `json:"byBaselineState"`
}

// TemplateFinding is the finding shape exposed to TemplateData v1.
type TemplateFinding struct {
	ID          string `json:"id"`
	Source      string `json:"source"`
	Tool        string `json:"tool"`
	ToolVersion string `json:"toolVersion"`

	RuleID          string `json:"ruleID"`
	RuleName        string `json:"ruleName"`
	RuleDescription string `json:"ruleDescription"`
	RuleHelpURI     string `json:"ruleHelpURI"`

	Level   string `json:"level"`
	Message string `json:"message"`

	Path      string `json:"path"`
	URI       string `json:"uri"`
	URIBaseID string `json:"uriBaseID"`

	StartLine   int `json:"startLine"`
	StartColumn int `json:"startColumn"`
	EndLine     int `json:"endLine"`
	EndColumn   int `json:"endColumn"`

	Snippet       string `json:"snippet"`
	Fingerprint   string `json:"fingerprint"`
	BaselineState string `json:"baselineState"`
	IsBaseline    bool   `json:"isBaseline"`
	SourceLink    string `json:"sourceLink"`

	RelatedLocations []TemplateRelatedLocation `json:"relatedLocations"`
	CodeFlows        []TemplateCodeFlow        `json:"codeFlows"`
}

// TemplateRelatedLocation is a secondary location exposed to TemplateData v1.
type TemplateRelatedLocation struct {
	Message     string `json:"message"`
	Path        string `json:"path"`
	URI         string `json:"uri"`
	StartLine   int    `json:"startLine"`
	StartColumn int    `json:"startColumn"`
}

// TemplateCodeFlow is a normalized execution path exposed to TemplateData v1.
type TemplateCodeFlow struct {
	Locations []TemplateRelatedLocation `json:"locations"`
}

// Count is a named aggregate used by filters, summaries, and custom templates.
type Count struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

// ToolGroup contains findings grouped by their normalized tool name.
type ToolGroup struct {
	Name     string            `json:"name"`
	Count    int               `json:"count"`
	Findings []TemplateFinding `json:"findings"`
}

// TemplateBaseline describes baseline behavior and aggregate counts for
// TemplateData v1.
type TemplateBaseline struct {
	Enabled                bool           `json:"enabled"`
	HideUnchangedByDefault bool           `json:"hideUnchangedByDefault"`
	Unchanged              int            `json:"unchanged"`
	New                    int            `json:"new"`
	ByState                map[string]int `json:"byState"`
	States                 []Count        `json:"states"`
}

// NewTemplateData builds the TemplateData v1 contract from normalized report
// data and render options.
func NewTemplateData(reportData report.Report, options Options) TemplateData {
	title := options.Title
	if title == "" {
		title = reportData.Title
	}
	if title == "" {
		title = "SARIF HTML Report"
	}
	templateReport := newTemplateReport(reportData, options)

	return TemplateData{
		SchemaVersion: TemplateDataVersion,
		Report:        templateReport,
		Title:         title,
		GeneratedAt:   time.Now().UTC().Format(time.RFC3339),
		Severities:    orderedCounts(reportData.Summary.BySeverity, []string{"error", "warning", "note", "none"}),
		Sources:       orderedCounts(countBySource(templateReport.Findings), nil),
		ToolGroups:    groupedFindingsByTool(templateReport.Findings),
		Rules:         orderedCounts(reportData.Summary.ByRule, nil),
		Files:         orderedCounts(reportData.Summary.ByFile, nil),
		Baseline:      newTemplateBaseline(reportData),
	}
}

func newTemplateReport(reportData report.Report, options Options) TemplateReport {
	findings := make([]TemplateFinding, 0, len(reportData.Findings))
	for _, finding := range reportData.Findings {
		findings = append(findings, newTemplateFinding(finding, options))
	}

	return TemplateReport{
		Title:    reportData.Title,
		Sources:  append([]string(nil), reportData.Sources...),
		Findings: findings,
		Summary: TemplateSummary{
			Total:           reportData.Summary.Total,
			BySeverity:      cloneCounts(reportData.Summary.BySeverity),
			ByTool:          cloneCounts(reportData.Summary.ByTool),
			ByRule:          cloneCounts(reportData.Summary.ByRule),
			ByFile:          cloneCounts(reportData.Summary.ByFile),
			ByBaselineState: cloneCounts(reportData.Summary.ByBaselineState),
		},
	}
}

func newTemplateFinding(finding report.Finding, options Options) TemplateFinding {
	relatedLocations := make([]TemplateRelatedLocation, 0, len(finding.RelatedLocations))
	for _, location := range finding.RelatedLocations {
		relatedLocations = append(relatedLocations, TemplateRelatedLocation{
			Message:     location.Message,
			Path:        location.Path,
			URI:         location.URI,
			StartLine:   location.StartLine,
			StartColumn: location.StartColumn,
		})
	}

	codeFlows := make([]TemplateCodeFlow, 0, len(finding.CodeFlows))
	for _, flow := range finding.CodeFlows {
		locations := make([]TemplateRelatedLocation, 0, len(flow.Locations))
		for _, location := range flow.Locations {
			locations = append(locations, TemplateRelatedLocation{
				Message:     location.Message,
				Path:        location.Path,
				URI:         location.URI,
				StartLine:   location.StartLine,
				StartColumn: location.StartColumn,
			})
		}
		codeFlows = append(codeFlows, TemplateCodeFlow{Locations: locations})
	}

	templateFinding := TemplateFinding{
		ID:               finding.ID,
		Source:           finding.Source,
		Tool:             finding.Tool,
		ToolVersion:      finding.ToolVersion,
		RuleID:           finding.RuleID,
		RuleName:         finding.RuleName,
		RuleDescription:  finding.RuleDescription,
		RuleHelpURI:      finding.RuleHelpURI,
		Level:            finding.Level,
		Message:          finding.Message,
		Path:             finding.Path,
		URI:              finding.URI,
		URIBaseID:        finding.URIBaseID,
		StartLine:        finding.StartLine,
		StartColumn:      finding.StartColumn,
		EndLine:          finding.EndLine,
		EndColumn:        finding.EndColumn,
		Snippet:          finding.Snippet,
		Fingerprint:      finding.Fingerprint,
		BaselineState:    finding.BaselineState,
		IsBaseline:       report.IsBaselineFinding(finding),
		RelatedLocations: relatedLocations,
		CodeFlows:        codeFlows,
	}
	templateFinding.SourceLink = sourceLink(templateFinding, options)
	return templateFinding
}

func newTemplateBaseline(reportData report.Report) TemplateBaseline {
	byState := cloneCounts(reportData.Summary.ByBaselineState)
	if byState == nil {
		byState = map[string]int{}
	}
	return TemplateBaseline{
		Enabled:                len(byState) > 0,
		HideUnchangedByDefault: byState[report.BaselineStateUnchanged] > 0,
		Unchanged:              byState[report.BaselineStateUnchanged],
		New:                    byState[report.BaselineStateNew],
		ByState:                byState,
		States:                 orderedCounts(byState, []string{report.BaselineStateNew, report.BaselineStateUpdated, report.BaselineStateUnchanged, report.BaselineStateAbsent}),
	}
}

func cloneCounts(values map[string]int) map[string]int {
	if values == nil {
		return nil
	}
	result := make(map[string]int, len(values))
	for key, value := range values {
		result[key] = value
	}
	return result
}

func loadTemplate(templatePath string, options Options) (*template.Template, error) {
	tmpl := template.New("report").Funcs(templateFuncs(options))
	if strings.TrimSpace(templatePath) == "" {
		parsed, err := tmpl.Parse(pageTemplate)
		if err != nil {
			return nil, fmt.Errorf("parse default HTML template: %w", err)
		}
		return parsed, nil
	}

	info, err := os.Stat(templatePath)
	if err != nil {
		return nil, fmt.Errorf("stat HTML template %s: %w", templatePath, err)
	}
	if info.IsDir() {
		return loadTemplateDirectory(tmpl, templatePath)
	}
	return loadTemplateFile(tmpl, templatePath)
}

func templateFuncs(options Options) template.FuncMap {
	return template.FuncMap{
		"severityClass": severityClass,
		"line":          line,
		"sourceLink": func(finding any) string {
			return sourceLink(finding, options)
		},
		"hasDetails": hasDetails,
	}
}

func loadTemplateFile(tmpl *template.Template, templatePath string) (*template.Template, error) {
	content, err := os.ReadFile(templatePath)
	if err != nil {
		return nil, fmt.Errorf("read HTML template %s: %w", templatePath, err)
	}
	parsed, err := tmpl.Parse(string(content))
	if err != nil {
		return nil, fmt.Errorf("parse HTML template %s: %w", templatePath, err)
	}
	return parsed, nil
}

func loadTemplateDirectory(tmpl *template.Template, templatePath string) (*template.Template, error) {
	files, err := templateFiles(templatePath)
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("parse HTML template directory %s: no .tmpl, .gotmpl, or .html files found", templatePath)
	}

	var combined strings.Builder
	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			return nil, fmt.Errorf("read HTML template %s: %w", file, err)
		}
		combined.Write(content)
		combined.WriteString("\n")
	}

	parsed, err := tmpl.Parse(combined.String())
	if err != nil {
		return nil, fmt.Errorf("parse HTML template directory %s: %w", templatePath, err)
	}
	return parsed, nil
}

func templateFiles(root string) ([]string, error) {
	var files []string
	if err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		if isTemplateFile(path) {
			files = append(files, path)
		}
		return nil
	}); err != nil {
		return nil, fmt.Errorf("scan HTML template directory %s: %w", root, err)
	}
	sort.Strings(files)
	return files, nil
}

func isTemplateFile(path string) bool {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".tmpl", ".gotmpl", ".html":
		return true
	default:
		return false
	}
}

// orderedCounts returns preferred names first, then every remaining key in
// lexical order. This keeps severity cards predictable while preserving stable
// ordering for dynamic facets such as tools and files.
func orderedCounts(values map[string]int, preferred []string) []Count {
	result := make([]Count, 0, len(values))
	seen := map[string]bool{}
	for _, name := range preferred {
		if value, ok := values[name]; ok {
			result = append(result, Count{Name: name, Count: value})
			seen[name] = true
		}
	}

	keys := make([]string, 0, len(values))
	for key := range values {
		if !seen[key] {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	for _, key := range keys {
		result = append(result, Count{Name: key, Count: values[key]})
	}
	return result
}

// countBySource derives source counts from findings rather than trusting report
// metadata, which keeps the facet accurate after merging.
func countBySource(findings []TemplateFinding) map[string]int {
	result := map[string]int{}
	for _, finding := range findings {
		source := strings.TrimSpace(finding.Source)
		if source == "" {
			source = "unknown-source"
		}
		result[source]++
	}
	return result
}

// groupedFindingsByTool powers the compact dashboard view. Groups with more
// findings appear first so the densest tool output is easiest to spot.
func groupedFindingsByTool(findings []TemplateFinding) []ToolGroup {
	byTool := map[string][]TemplateFinding{}
	for _, finding := range findings {
		tool := strings.TrimSpace(finding.Tool)
		if tool == "" {
			tool = "unknown-tool"
		}
		byTool[tool] = append(byTool[tool], finding)
	}

	groups := make([]ToolGroup, 0, len(byTool))
	for tool, toolFindings := range byTool {
		groups = append(groups, ToolGroup{Name: tool, Count: len(toolFindings), Findings: toolFindings})
	}
	sort.SliceStable(groups, func(i, j int) bool {
		if groups[i].Count != groups[j].Count {
			return groups[i].Count > groups[j].Count
		}
		return groups[i].Name < groups[j].Name
	})
	return groups
}

// severityClass maps normalized severities to CSS classes used by the template.
func severityClass(level string) string {
	switch strings.ToLower(level) {
	case "error":
		return "sev-error"
	case "warning":
		return "sev-warning"
	case "note":
		return "sev-note"
	case "none":
		return "sev-none"
	default:
		return "sev-unknown"
	}
}

// line formats absent SARIF line numbers as a compact placeholder for tables.
func line(value int) string {
	if value <= 0 {
		return "-"
	}
	return fmt.Sprint(value)
}

// hasDetails controls whether a finding renders the collapsible detail section.
func hasDetails(finding any) bool {
	switch value := finding.(type) {
	case TemplateFinding:
		return value.RuleDescription != "" || value.RuleHelpURI != "" || value.Snippet != "" || len(value.RelatedLocations) > 0 || len(value.CodeFlows) > 0
	case report.Finding:
		return value.RuleDescription != "" || value.RuleHelpURI != "" || value.Snippet != "" || len(value.RelatedLocations) > 0 || len(value.CodeFlows) > 0
	default:
		return false
	}
}

// sourceLink returns the best clickable location for a finding. Explicit HTTP
// SARIF URIs win, followed by custom templates, then GitHub/GitLab-style repo
// links when repository metadata is available.
func sourceLink(finding any, options Options) string {
	data, ok := findingLinkDataFor(finding)
	if !ok {
		return ""
	}
	if strings.HasPrefix(data.URI, "http://") || strings.HasPrefix(data.URI, "https://") {
		return data.URI
	}
	if data.Path == "" {
		return ""
	}

	if options.SourceURLTemplate != "" {
		return sourceLinkFromTemplate(options.SourceURLTemplate, data, options)
	}

	if options.RepoURL == "" || options.Revision == "" {
		return ""
	}

	base := strings.TrimSuffix(options.RepoURL, "/")
	base = strings.TrimSuffix(base, ".git")
	escapedPath := escapePath(data.Path)

	if strings.Contains(base, "gitlab.") || strings.Contains(base, "gitlab.com") {
		return fmt.Sprintf("%s/-/blob/%s/%s%s", base, url.PathEscape(options.Revision), escapedPath, lineFragment(data))
	}
	return fmt.Sprintf("%s/blob/%s/%s%s", base, url.PathEscape(options.Revision), escapedPath, lineFragment(data))
}

type findingLinkData struct {
	URI         string
	Path        string
	StartLine   int
	StartColumn int
	EndLine     int
	EndColumn   int
}

func findingLinkDataFor(finding any) (findingLinkData, bool) {
	switch value := finding.(type) {
	case TemplateFinding:
		return findingLinkData{
			URI:         value.URI,
			Path:        value.Path,
			StartLine:   value.StartLine,
			StartColumn: value.StartColumn,
			EndLine:     value.EndLine,
			EndColumn:   value.EndColumn,
		}, true
	case report.Finding:
		return findingLinkData{
			URI:         value.URI,
			Path:        value.Path,
			StartLine:   value.StartLine,
			StartColumn: value.StartColumn,
			EndLine:     value.EndLine,
			EndColumn:   value.EndColumn,
		}, true
	default:
		return findingLinkData{}, false
	}
}

// sourceLinkFromTemplate replaces documented placeholders without trying to
// parse the URL. This keeps custom schemes such as editor:// usable.
func sourceLinkFromTemplate(template string, finding findingLinkData, options Options) string {
	replacements := map[string]string{
		"{path}":         escapePath(finding.Path),
		"{pathRaw}":      strings.TrimLeft(finding.Path, "/"),
		"{line}":         positiveInt(finding.StartLine),
		"{startLine}":    positiveInt(finding.StartLine),
		"{endLine}":      positiveInt(finding.EndLine),
		"{column}":       positiveInt(finding.StartColumn),
		"{startColumn}":  positiveInt(finding.StartColumn),
		"{endColumn}":    positiveInt(finding.EndColumn),
		"{revision}":     url.PathEscape(options.Revision),
		"{revisionRaw}":  options.Revision,
		"{lineFragment}": lineFragment(finding),
	}

	result := template
	for placeholder, value := range replacements {
		result = strings.ReplaceAll(result, placeholder, value)
	}
	return result
}

// escapePath escapes path segments while preserving slashes between segments.
func escapePath(rawPath string) string {
	escapedPath := strings.TrimLeft(rawPath, "/")
	parts := strings.Split(escapedPath, "/")
	for index, part := range parts {
		parts[index] = url.PathEscape(part)
	}
	return strings.Join(parts, "/")
}

// lineFragment returns the GitHub/GitLab-style line anchor for a finding.
func lineFragment(finding findingLinkData) string {
	if finding.StartLine <= 0 {
		return ""
	}
	if finding.EndLine > finding.StartLine {
		return fmt.Sprintf("#L%d-L%d", finding.StartLine, finding.EndLine)
	}
	return fmt.Sprintf("#L%d", finding.StartLine)
}

// positiveInt renders SARIF's optional numeric fields as empty placeholders
// when their zero value means "not provided".
func positiveInt(value int) string {
	if value <= 0 {
		return ""
	}
	return fmt.Sprint(value)
}
